Repository 10up/autoshare-for-twitter, pull requests merged in 2020-01, with the labels that each got.

#61 add back .org plugin assets
  .wordpress-org/banner-1544x500.png
  .wordpress-org/banner-772x250.png
  .wordpress-org/icon-128x128.png
  .wordpress-org/icon-256x256.png
  .wordpress-org/icon.svg
Labels: bug

#62 update formatting for dotorg display of readme.txt
  readme.txt
Labels: bug, documentation

#65 Improve display on WordPress.ORG
  .wordpress-org/icon-128x128.png
  .wordpress-org/icon-256x256.png
  .wordpress-org/icon.svg
  readme.txt
Labels: documentation

#70 Remove WP filter unnecessarily applied twice
  includes/class-publish-tweet.php
Labels: bug

#71 Add filter to allow autoshare to be enabled by default for a post type
  README.md
  includes/admin/assets.php
  includes/admin/post-meta.php
  includes/admin/post-transition.php
  includes/utils.php
  src/js/store/reducer.js
Labels: enhancement

#74 README.md formatting fix
  README.md
Labels: documentation
